#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


PLACEHOLDER_RE = re.compile(r"<[a-z0-9_]+>")
PLACEHOLDER_KEY_RE = re.compile(r"[a-z0-9_]+")


def parse_yaml_scalar(value: str) -> str:
    if value.startswith("'"):
        if not value.endswith("'"):
            raise ValueError(f"unterminated single-quoted scalar: {value}")

        return value[1:-1].replace("''", "'")

    if value.startswith('"'):
        raise ValueError("double-quoted scalars are not supported; use single quotes")

    return value


def read_data(path: Path) -> tuple[dict[str, str], list[str], list[str]]:
    placeholders: dict[str, str] = {}
    templates: list[str] = []
    silly_billy: list[str] = []
    section: str | None = None

    for line_number, raw_line in enumerate(path.read_text().splitlines(), start=1):
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue

        if section == "templates" and raw_line.startswith("- "):
            templates.append(parse_yaml_scalar(raw_line.removeprefix("- ").strip()))
            continue

        if not raw_line.startswith(" "):
            if raw_line == "placeholders:":
                section = "placeholders"
                continue

            if raw_line == "templates:":
                section = "templates"
                continue

            if raw_line == "silly-billy:":
                section = "silly-billy"
                continue

            if re.fullmatch(r"[a-z0-9_-]+:", raw_line):
                section = None
                continue

            raise ValueError(f"{path}:{line_number}: unsupported top-level YAML line: {raw_line}")

        if section == "placeholders":
            line = raw_line.strip()

            if ": " not in line:
                raise ValueError(f"{path}:{line_number}: expected 'name: regex'")

            name, regex = line.split(": ", 1)

            if not PLACEHOLDER_KEY_RE.fullmatch(name):
                raise ValueError(f"{path}:{line_number}: invalid placeholder name: {name}")

            placeholders[f"<{name}>"] = parse_yaml_scalar(regex)
            continue

        if section == "templates":
            line = raw_line.strip()

            if not line.startswith("- "):
                raise ValueError(f"{path}:{line_number}: expected '- template'")

            templates.append(parse_yaml_scalar(line.removeprefix("- ").strip()))
            continue

        if section == "silly-billy":
            line = raw_line.strip()

            if ": " not in line:
                raise ValueError(f"{path}:{line_number}: expected 'name: template'")

            name, template = line.split(": ", 1)

            if not re.fullmatch(r"[a-z0-9_-]+", name):
                raise ValueError(f"{path}:{line_number}: invalid silly-billy name: {name}")

            silly_billy.append(parse_yaml_scalar(template))
            continue

        if section is None:
            continue

        raise ValueError(f"{path}:{line_number}: data before section")

    if not placeholders:
        raise ValueError(f"{path}: missing placeholders")

    if not templates:
        raise ValueError(f"{path}: missing templates")

    return placeholders, templates, silly_billy


def pattern_to_regex(pattern: str, placeholders: dict[str, str]) -> str:
    parts: list[str] = []
    cursor = 0

    for match in PLACEHOLDER_RE.finditer(pattern):
        parts.append(re.escape(pattern[cursor:match.start()]))

        placeholder = match.group(0)
        if placeholder not in placeholders:
            raise ValueError(f"missing placeholder regex for {placeholder}")

        parts.append(f"({placeholders[placeholder]})")
        cursor = match.end()

    parts.append(re.escape(pattern[cursor:]))

    return "^" + "".join(parts) + "$"


def quote_apache_regex(regex: str) -> str:
    return regex.replace('"', '\\"')


def regexes_to_apache_setenvif(regexes: list[str]) -> str:
    lines = [
        "# Generated by generate-user-agent-regexes.py.",
        "# Include this file from Apache server or virtual host config.",
    ]

    for regex in regexes:
        lines.append(
            f'SetEnvIf User-Agent "{quote_apache_regex(regex)}" well_formed_user_agent=1'
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate real regexes from known user-agent patterns."
    )
    parser.add_argument(
        "--data",
        default="well-formed-user-agent-templates.yaml",
        type=Path,
        help="YAML file containing placeholders and well-formed user-agent templates.",
    )
    parser.add_argument(
        "--output",
        default="well-formed-user-agent-regexes.txt",
        type=Path,
        help="Output file for generated regexes.",
    )
    parser.add_argument(
        "--apache-output",
        default="well-formed-user-agent-apache.conf",
        type=Path,
        help="Output Apache SetEnvIf include file.",
    )
    parser.add_argument(
        "--silly-billy",
        action="store_true",
        help="Also generate regexes from the known not well-formed UA patterns.",
    )
    args = parser.parse_args()

    placeholders, templates, silly_billy = read_data(args.data)
    patterns = templates + silly_billy if args.silly_billy else templates
    regexes = [pattern_to_regex(pattern, placeholders) for pattern in patterns]

    args.output.write_text("\n".join(regexes) + "\n")
    args.apache_output.write_text(regexes_to_apache_setenvif(regexes))


if __name__ == "__main__":
    main()
